### ISSUE TITLE
libusb nut drivers broken after trying to install twili

### ISSUE THREAD

**Issue by VelocityRa** [misson20000/twili#92]
I'm on Windows, I tried to install twili drivers from [here](https://github.com/misson20000/twili/tree/master/contrib/windows/driver) to get it working but had some issues, Device Manager said that it couldn't find a file when trying to install the drivers.

I never got it working but that's not what the issue is about. I can't use [nut](https://github.com/blawar/nut) at all now and "libnx comms device" doesn't even appear in Zadig anymore.

I've tried uninstalling every related USB device & drivers i can see from Device Manager to no avail.

Any ideas on how I can fix this? Thanks.

**Comment by misson20000** [comment]
I'm have no idea what the problem might be. Windows support is notoriously bad because the whole driver situation gives me a headache and I prefer not to deal with it, and I also prefer not to deal with piracy tools. The only thing I can think to suggest is that you should make sure you're not trying to run two things that use USB on the switch at the same time. I would not expect that to work very well.
